//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EZenGnssProperty {
  ZenGnssProperty_Invalid = 0,
  ZenGnnsProperty_OutputNavPvtiTOW,
  ZenGnnsProperty_OutputNavPvtYear,
  ZenGnnsProperty_OutputNavPvtMonth,
  ZenGnnsProperty_OutputNavPvtDay,
  ZenGnnsProperty_OutputNavPvtHour,
  ZenGnnsProperty_OutputNavPvtMinute,
  ZenGnnsProperty_OutputNavPvtSecond,
  ZenGnnsProperty_OutputNavPvtValid,
  ZenGnnsProperty_OutputNavPvttAcc,
  ZenGnnsProperty_OutputNavPvtNano,
  ZenGnnsProperty_OutputNavPvtFixType,
  ZenGnnsProperty_OutputNavPvtFlags,
  ZenGnnsProperty_OutputNavPvtFlags2,
  ZenGnnsProperty_OutputNavPvtNumSV,
  ZenGnnsProperty_OutputNavPvtLongitude,
  ZenGnnsProperty_OutputNavPvtLatitude,
  ZenGnnsProperty_OutputNavPvtHeight,
  ZenGnnsProperty_OutputNavPvthMSL,
  ZenGnnsProperty_OutputNavPvthAcc,
  ZenGnnsProperty_OutputNavPvtvAcc,
  ZenGnnsProperty_OutputNavPvtVelN,
  ZenGnnsProperty_OutputNavPvtVelE,
  ZenGnnsProperty_OutputNavPvtVelD,
  ZenGnnsProperty_OutputNavPvtgSpeed,
  ZenGnnsProperty_OutputNavPvtHeadMot,
  ZenGnnsProperty_OutputNavPvtsAcc,
  ZenGnnsProperty_OutputNavPvtHeadAcc,
  ZenGnnsProperty_OutputNavPvtpDOP,
  ZenGnnsProperty_OutputNavPvtHeadVeh,
  ZenGnnsProperty_OutputNavAttiTOW,
  ZenGnnsProperty_OutputNavAttVersion,
  ZenGnnsProperty_OutputNavAttRoll,
  ZenGnnsProperty_OutputNavAttPitch,
  ZenGnnsProperty_OutputNavAttHeading,
  ZenGnnsProperty_OutputNavAttAccRoll,
  ZenGnnsProperty_OutputNavAttAccPitch,
  ZenGnnsProperty_OutputNavAttAccHeading,
  ZenGnnsProperty_OutputEsfStatusiTOW,
  ZenGnnsProperty_OutputEsfStatusVersion,
  ZenGnnsProperty_OutputEsfStatusInitStatus1,
  ZenGnnsProperty_OutputEsfStatusInitStatus2,
  ZenGnnsProperty_OutputEsfStatusFusionMode,
  ZenGnnsProperty_OutputEsfStatusNumSens,
  ZenGnnsProperty_OutputEsfStatusSensStatus,
  ZenGnssProperty_Max
}
