//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EZenImuProperty {
  ZenImuProperty_Invalid = 0,
  ZenImuProperty_StreamData = 1000,
  ZenImuProperty_SamplingRate,
  ZenImuProperty_SupportedSamplingRates,
  ZenImuProperty_PollSensorData,
  ZenImuProperty_CalibrateGyro,
  ZenImuProperty_ResetOrientationOffset,
  ZenImuProperty_CentricCompensationRate,
  ZenImuProperty_LinearCompensationRate,
  ZenImuProperty_FieldRadius,
  ZenImuProperty_FilterMode,
  ZenImuProperty_SupportedFilterModes,
  ZenImuProperty_FilterPreset,
  ZenImuProperty_OrientationOffsetMode,
  ZenImuProperty_AccAlignment,
  ZenImuProperty_AccBias,
  ZenImuProperty_AccRange,
  ZenImuProperty_AccSupportedRanges,
  ZenImuProperty_GyrAlignment,
  ZenImuProperty_GyrBias,
  ZenImuProperty_GyrRange,
  ZenImuProperty_GyrSupportedRanges,
  ZenImuProperty_GyrUseAutoCalibration,
  ZenImuProperty_GyrUseThreshold,
  ZenImuProperty_MagAlignment,
  ZenImuProperty_MagBias,
  ZenImuProperty_MagRange,
  ZenImuProperty_MagSupportedRanges,
  ZenImuProperty_MagReference,
  ZenImuProperty_MagHardIronOffset,
  ZenImuProperty_MagSoftIronMatrix,
  ZenImuProperty_OutputLowPrecision,
  ZenImuProperty_OutputRawAcc,
  ZenImuProperty_OutputRawGyr,
  ZenImuProperty_OutputRawMag,
  ZenImuProperty_OutputEuler,
  ZenImuProperty_OutputQuat,
  ZenImuProperty_OutputAngularVel,
  ZenImuProperty_OutputLinearAcc,
  ZenImuProperty_OutputHeaveMotion,
  ZenImuProperty_OutputAltitude,
  ZenImuProperty_OutputPressure,
  ZenImuProperty_OutputTemperature,
  ZenImuProperty_Max
}
