//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenGnssEvent {
  ZenGnssEvent_None = 0,
  ZenGnssEvent_Sample = 1,
  ZenGnssEvent_ComponentSpecific_Start = 10000,
  ZenGnssEvent_ComponentSpecific_End = 19999,
  ZenGnssEvent_Max
}
