//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenImuEvent {
  ZenImuEvent_None = 0,
  ZenImuEvent_Sample = 1,
  ZenImuEvent_ComponentSpecific_Start = 10000,
  ZenImuEvent_ComponentSpecific_End = 19999,
  ZenImuEvent_Max
}
