//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenSensorEvent {
  ZenSensorEvent_None = 0,
  ZenSensorEvent_SensorFound = 1,
  ZenSensorEvent_SensorListingProgress = 2,
  ZenSensorEvent_SensorDisconnected = 3,
  ZenSensorEvent_SensorSpecific_Start = 10000,
  ZenSensorEvent_SensorSpecific_End = 19999,
  ZenSensorEvent_Max
}
